# Generated by Django 5.1.1 on 2024-10-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Humedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("humedad_bits", models.CharField(max_length=20)),
                ("humedad_analog", models.CharField(max_length=20)),
            ],
        ),
    ]
